name: Run Tests

on:
  push:
    branches:
      - devel
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read  # Needed to pull GHCR images
    
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 1 || 2 }}

      # Uses this step to check which files have been changed by the
      # current push. If there are no source files than skip
      - name: ➕ Check Source file changes
        id: file-change-step
        uses: tj-actions/changed-files@v47
        with:
          files_ignore: |
            .vscode/**
            .devcontainer/**
            .gitignore
            LICENSE
            **/*.md

      - name: 🔐 Log in to GHCR
        if: steps.file-change-step.outputs.all_changed_files_count != '0'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if image exists
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/spatial-container:latest
          if ! docker manifest inspect $IMAGE > /dev/null 2>&1; then
            echo "Image does not exist. Skipping tests."
            exit 78
          fi

      - name: 🐳 Pull Docker Image
        run: |
          docker pull ghcr.io/${{ github.repository }}/spatial-container:latest
      
      - name: ✅ Run CTests inside the container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ghcr.io/${{ github.repository }}/spatial-container:latest \
            bash -c "
              mkdir -p build &&
              cmake -S . -B build -DCMAKE_BUILD_TYPE=Release &&
              cmake --build build --config Release &&
              ctest --test-dir build --output-on-failure -C Release \
                --output-junit test_results.xml
            "
      
      - name: 🏵️ Generate Custom Test Badge
        uses: gaelgirodon/ci-badges-action@v1
        if: always()
        with:
          gist-id: ${{ secrets.TEST_BADGE_GIST_ID }}
          token: ${{ secrets.GIST_TOKEN }}

      - name: ➖ No Changed Files
        if: steps.file-change-step.outputs.all_changed_files_count == '0'
        run: echo "No source files have been changed!!"